#import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[shell]
program = "/home/tim/.nix-profile/bin/fish"

[font]
size = 12

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font Mono"

[window]
#decorations = "none"
dynamic_title = true
dimensions = { columns = 100, lines = 50 }
position =  { x = 4600, y = 1200 }


