#import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[shell]
program = "/home/tim/.nix-profile/bin/fish"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font Mono"

[window]
#decorations = "none"
dynamic_title = true
