#!/bin/zsh

# NOTE: this is sourced by bashrc so ensure it is compatible

#~~ capture original PATH
if [[ -z "$PATH_BASE" ]]; then
  export PATH_BASE="$PATH"
fi

#~~ append to $PATH idempotently...
function add_to_path {
  for dir in "$@"; do
    if [[ ":$PATH:" != *":$dir:"* ]]; then
      export PATH="$PATH:$dir"
    fi
  done
}

# Read the paths from the paths.config file and add them to PATH
while IFS= read -r line; do
  # Trim leading and trailing whitespace
  line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  # Ignore empty lines, lines with only whitespace, and lines starting with #
  if [[ -n "$line" && ! "$line" =~ ^# ]]; then
    paths_array+=("$line")
  fi
done < $HOME/.path.config

#~~ reset PATH and rebuild it
export PATH="$PATH_BASE"
add_to_path "${paths_array[@]}"

function print_path {
  echo "$PATH" | tr ':' '\n' | sort
}
alias ppath="print_path"

#~~ add cargo bin dir to PATH
# need to use this method for some reason, instead of declaring the bin dir in .path.config
if [[ -f $HOME/.cargo/env ]]; then
  source $HOME/.cargo/env
fi

#~~ misc aliases
alias mp="mkdir -p"
if command -v lsd >/dev/null 2>&1; then
  alias ls="lsd"
fi
alias ll="ls -l"
alias la="ls -la"
alias l="ll"