#!/bin/zsh

packages=(
  ts-node@latest
  prettier@latest
  opencommit@latest
  chatgpt-cli@latest
  @anthropic-ai/claude-code@latest
  @fission-ai/openspec@latest
  npm-check-updates@latest
  typescript@latest
  typescript-language-server@latest
)

pnpm i -g "${packages[@]}"
