#!/bin/zsh
set -o pipefail

source $HOME/.config/local.sh

# ~~~~ SETUP ~~~~ #
# ~~~~~~~~~~~~~~~ #

# install xcode command line tools
xcode-select --install || true

# create default zshrc file
touch ~/.zshrc

# install homebrew
if ! command -v /opt/homebrew/bin/brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo 'PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
    source ~/.zshrc
fi

$DOTFILES_ROOT/scripts/brew-update

# setup .config sync with stow
cd $DOTFILES_ROOT && stow --target $HOME src
cd -
# chsh -s $(which fish)

cat <<EOF | fish

# if ! type -q fisher
  echo "Installing fisher"
  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source \
    && fisher install jorgebucaran/fisher
# end
# update/install fisher_plugins from file
fisher update

# install powerline fonts
# see: https://github.com/powerline/powerline
if ! ls $HOME/Library/Fonts | grep -qi powerline
  git clone https://github.com/powerline/fonts.git powerline-fonts \
    && cd powerline-fonts \
    && ./install.sh \
    && cd - \
    && rm -rf powerline-fonts
end

EOF

# install nvm
if ! command -v nvm &> /dev/null; then
  PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash'
  source $HOME/.nvm/nvm.sh
  nvm install $NODE_VERSION
  nvm use $NODE_VERSION
fi

# install rust
if ! command -v rustup &> /dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  source $HOME/.cargo/env
fi

$DOTFILES_ROOT/scripts/cargo-update

# add fonts
$DOTFILES_ROOT/scripts/install-fonts-mac

# install alacritty terminal emulator
if ! command -v alacritty &> /dev/null; then
  $DOTFILES_ROOT/scripts/install-alacritty-mac
fi

# override system bash
#rm /bin/bash
#ln -s /opt/homebrew/bin/bash /bin/bash
